//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DayNightMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DayNightMgr), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Switch", Switch);
		L.RegFunction("SetParams", SetParams);
		L.RegFunction("ResetParams", ResetParams);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Switch(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 6);
			DayNightMgr obj = (DayNightMgr)ToLua.CheckObject(L, 1, typeof(DayNightMgr));
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			float arg3 = (float)LuaDLL.luaL_checknumber(L, 5);
			float arg4 = (float)LuaDLL.luaL_checknumber(L, 6);
			obj.Switch(arg0, arg1, arg2, arg3, arg4);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetParams(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			DayNightMgr obj = (DayNightMgr)ToLua.CheckObject(L, 1, typeof(DayNightMgr));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.SetParams(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetParams(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DayNightMgr obj = (DayNightMgr)ToLua.CheckObject(L, 1, typeof(DayNightMgr));
			obj.ResetParams();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, DayNightMgr.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

