//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LayerHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("LayerHelper");
		L.RegFunction("ApplyLayerTo", ApplyLayerTo);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ApplyLayerTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.GameObject));
			bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
			LayerHelper.ApplyLayerTo(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

