//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AnimationMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AnimationMgr), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("PlayAni", PlayAni);
		L.RegFunction("GetAniTime", GetAniTime);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayAni(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AnimationMgr obj = (AnimationMgr)ToLua.CheckObject(L, 1, typeof(AnimationMgr));
			string arg0 = ToLua.CheckString(L, 2);
			obj.PlayAni(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAniTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AnimationMgr obj = (AnimationMgr)ToLua.CheckObject(L, 1, typeof(AnimationMgr));
			string arg0 = ToLua.CheckString(L, 2);
			float o = obj.GetAniTime(arg0);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

