//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class HanderComWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(HanderCom), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("CrossAni", CrossAni);
		L.RegFunction("PlayAni", PlayAni);
		L.RegFunction("GetAniTime", GetAniTime);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("ani", get_ani, set_ani);
		L.RegVar("centerFinger", get_centerFinger, set_centerFinger);
		L.RegVar("firstFinger", get_firstFinger, set_firstFinger);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CrossAni(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			HanderCom obj = (HanderCom)ToLua.CheckObject(L, 1, typeof(HanderCom));
			string arg0 = ToLua.CheckString(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.CrossAni(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayAni(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			HanderCom obj = (HanderCom)ToLua.CheckObject(L, 1, typeof(HanderCom));
			string arg0 = ToLua.CheckString(L, 2);
			obj.PlayAni(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAniTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			HanderCom obj = (HanderCom)ToLua.CheckObject(L, 1, typeof(HanderCom));
			string arg0 = ToLua.CheckString(L, 2);
			float o = obj.GetAniTime(arg0);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ani(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			HanderCom obj = (HanderCom)o;
			UnityEngine.Animation ret = obj.ani;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index ani on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_centerFinger(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			HanderCom obj = (HanderCom)o;
			UnityEngine.Transform ret = obj.centerFinger;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index centerFinger on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_firstFinger(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			HanderCom obj = (HanderCom)o;
			UnityEngine.Transform ret = obj.firstFinger;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index firstFinger on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ani(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			HanderCom obj = (HanderCom)o;
			UnityEngine.Animation arg0 = (UnityEngine.Animation)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.Animation));
			obj.ani = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index ani on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_centerFinger(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			HanderCom obj = (HanderCom)o;
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.Transform));
			obj.centerFinger = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index centerFinger on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_firstFinger(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			HanderCom obj = (HanderCom)o;
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.Transform));
			obj.firstFinger = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index firstFinger on a nil value" : e.Message);
		}
	}
}

