//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Asset_Script_Core_Singleton_LuaHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Asset.Script.Core.Singleton<LuaHelper>), typeof(System.Object), "Singleton_LuaHelper");
		L.RegFunction("New", _CreateAsset_Script_Core_Singleton_LuaHelper);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAsset_Script_Core_Singleton_LuaHelper(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Asset.Script.Core.Singleton<LuaHelper> obj = new Asset.Script.Core.Singleton<LuaHelper>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Asset.Script.Core.Singleton<LuaHelper>.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Asset.Script.Core.Singleton<LuaHelper>.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

