//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MagicWinWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("MagicWin");
		L.RegFunction("OnMagicWinMsg", OnMagicWinMsg);
		L.RegFunction("RegLuaCallBack", RegLuaCallBack);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnMagicWinMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			MagicWin.OnMagicWinMsg(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegLuaCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 1);
			MagicWin.RegLuaCallBack(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

